# Generated by Django 5.0.1 on 2025-12-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('Web Development', 'Web Development'), ('Machine Learning', 'Machine Learning'), ('Gen AI', 'Generative AI'), ('Android', 'Android Development'), ('Data Science', 'Data Science'), ('Blockchain', 'Blockchain'), ('AR/VR', 'AR/VR'), ('Embedded Systems', 'Embedded Systems')], max_length=50),
        ),
    ]
