# Generated by Django 5.0.1 on 2025-12-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_technology_remove_project_technology_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='long_description',
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(to='core.technology'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
