# Generated by Django 5.0.1 on 2025-12-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_project_long_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
        migrations.AddField(
            model_name='project',
            name='long_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='technology',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('Web Development', 'Web Development'), ('Machine Learning', 'Machine Learning'), ('Gen AI', 'Generative AI'), ('Android', 'Android Development'), ('Data Science', 'Data Science'), ('Blockchain', 'Blockchain'), ('AR/VR', 'AR/VR'), ('Embedded Systems', 'Embedded Systems')], default='Python', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
